In [163]:
def read_code(file):
    with open(file, 'r') as f:
        for l in f:
            ll = l.strip().split(',')
    return [int(v) for v in ll]
i5=read_code("i.txt") 
tt5=read_code("t.txt") 

a="3,9,8,9,10,9,4,9,99,-1,8"
b="3,9,7,9,10,9,4,9,99,-1,8"
c="3,3,1108,-1,8,3,4,3,99"
d="3,3,1107,-1,8,3,4,3,99"
e="3,12,6,12,15,1,13,14,13,4,13,99,-1,0,1,9"
f="3,3,1105,-1,9,1101,0,0,12,4,12,99,1"
g="3,21,1008,21,8,20,1005,20,22,107,8,21,20,1006,20,31,1106,0,36,98,0,0,1002,21,125,20,4,20,1105,1,46,104,999,1105,1,46,1101,1000,1,20,4,20,1105,1,46,98,99"
h="1002,4,3,4,33"

def mk_code(s):
    return [ int(v) for v in s.split(',')]

In [160]:
def get(mem, mode, i):
    if mode == 1:
        return mem[i]
    return mem[mem[i]]

def cmd(mem, i, cin, verbose=False):
    c = "0000"+str(mem[i])
    c = c[-5:]
    A, B, C, DE = int(c[0]), int(c[1]), int(c[2]), int(c[3:5])
    cout = 0
    A=1
    if DE in [1,2]:
        new_i = i+4 # op,v1, v2, target
        v1 = get(mem,C, i+1)
        v2 = get(mem,B, i+2)
        target = get(mem, 1, i+3)
        if verbose:
            print("run {} with {} {} -> {}".format(DE, v1, v2, target))
        mem[target] = v1+v2 if DE == 1 else v1*v2
    elif DE in [3,4]: # op, v
        new_i = i+2
        target = get(mem, 1, i+1)
        if verbose:
            print("run {} with {}".format(DE, target))
        if DE == 3:
            mem[target] = cin
        else:
            cout = mem[target]
    elif DE in [5,6]: # op, bool, v
        new_i = i+3
        jump = get(mem, C, i+1) != 0
        if (DE == 5 and jump) or (DE == 6 and not jump):
            v = get(mem, B, i+2)
            if verbose:
                print("run {} with {} -> {}".format(DE, jump, v))
            new_i = v
    elif DE in [7,8]: # op, v1, v2, target
        new_i = i+4
        v1 = get(mem,C, i+1)
        v2 = get(mem,B, i+2)
        target = get(mem, A, i+3)
        if verbose:
            print("run {} with {} {} -> {}".format(DE, v1, v2, target))
        mem[target] =  (v1 < v2 if DE == 7 else v1 == v2)*1
    else:
        print(mem[i])
    return mem, new_i, cout

def run(mem, cin):
    _code = mem[:]
    i = 0
    while _code[i] != 99:
        _code, i, c = cmd(_code, i, cin, True)
        if c != 0:
            return c
    return 0

In [165]:
run(i5, 5)

run 3 with 225
run 1 with 5 1100 -> 6
run 5 with True -> 238
run 5 with True -> 247
run 5 with True -> 256
run 6 with False -> 265
run 6 with False -> 274
run 5 with True -> 280
run 1 with 5 5 -> 225
run 1 with 294 0 -> 0
run 5 with True -> 294
run 6 with False -> 300
run 1 with 10 10 -> 225
run 1 with 314 0 -> 0
run 6 with False -> 314
run 7 with 677 677 -> 224
run 2 with 2 0 -> 223
run 1 with 1 0 -> 223
run 8 with 677 677 -> 224
run 2 with 2 1 -> 223
run 5 with True -> 344
run 8 with 226 677 -> 224
run 2 with 2 2 -> 223
run 1 with 4 1 -> 223
run 8 with 226 677 -> 224
run 2 with 2 5 -> 223
run 6 with False -> 374
run 7 with 226 677 -> 224
run 2 with 2 10 -> 223
run 1 with 1 20 -> 223
run 8 with 677 226 -> 224
run 2 with 21 2 -> 223
run 1 with 42 1 -> 223
run 8 with 677 226 -> 224
run 2 with 2 43 -> 223
run 1 with 1 86 -> 223
run 7 with 677 226 -> 224
run 2 with 87 2 -> 223
run 6 with False -> 434
run 7 with 226 226 -> 224
run 2 with 2 174 -> 223
run 1 with 1 348 -> 223
run 8 with 677 677 -> 224
run 2 with 349 2 -> 223
run 1 with 1 698 -> 223
run 7 with 226 677 -> 224
run 2 with 2 699 -> 223
run 1 with 1 1398 -> 223
run 7 with 226 677 -> 224
run 2 with 1399 2 -> 223
run 5 with True -> 494
run 8 with 677 226 -> 224
run 2 with 2 2798 -> 223
run 6 with False -> 509
run 7 with 677 226 -> 224
run 2 with 2 5596 -> 223
run 6 with False -> 524
run 8 with 677 677 -> 224
run 2 with 11192 2 -> 223
run 5 with True -> 539
run 7 with 226 226 -> 224
run 2 with 2 22384 -> 223
run 6 with False -> 554
run 7 with 677 226 -> 224
run 2 with 44768 2 -> 223
run 1 with 89536 1 -> 223
run 8 with 677 226 -> 224
run 2 with 89537 2 -> 223
run 6 with False -> 584
run 8 with 226 677 -> 224
run 2 with 179074 2 -> 223
run 6 with False -> 599
run 7 with 677 226 -> 224
run 2 with 358148 2 -> 223
run 1 with 716296 1 -> 223
run 7 with 226 677 -> 224
run 2 with 2 716297 -> 223
run 1 with 1432594 1 -> 223
run 8 with 677 677 -> 224
run 2 with 2 1432595 -> 223
run 5 with True -> 644
run 7 with 226 226 -> 224
run 2 with 2 2865190 -> 223
run 6 with False -> 659
run 8 with 226 677 -> 224
run 2 with 2 5730380 -> 223
run 6 with False -> 674
run 4 with 223

11460760

In [167]:
print("test equal in position mode")
assert run(mk_code(a),7) == 0
assert run(mk_code(a),8) == 1
print("test less in position mode")
assert run(mk_code(b),6) == 1
assert run(mk_code(b),9) == 0
print("test equal in immediate mode")
assert run(mk_code(c),7) == 0
assert run(mk_code(c),8) == 1
print("test less in immediate mode")
assert run(mk_code(d),6) == 1
assert run(mk_code(d),9) == 0
print("test jump in position mode")
assert run(mk_code(e),0) == 0
assert run(mk_code(e),9) == 1
print("test jump in immediate mode")
assert run(mk_code(f),0) == 0
assert run(mk_code(f),8) == 1
print("test bigger example")
#assert run(mk_code(g),7) == 999
assert run(mk_code(g),8) == 1000
assert run(mk_code(g),9) == 1001

test equal in position mode
run 3 with 9
run 8 with 7 8 -> 9
run 4 with 9
run 3 with 9
run 8 with 8 8 -> 9
run 4 with 9
test less in position mode
run 3 with 9
run 7 with 6 8 -> 9
run 4 with 9
run 3 with 9
run 7 with 9 8 -> 9
run 4 with 9
test equal in immediate mode
run 3 with 3
run 8 with 7 8 -> 3
run 4 with 3
run 3 with 3
run 8 with 8 8 -> 3
run 4 with 3
test less in immediate mode
run 3 with 3
run 7 with 6 8 -> 3
run 4 with 3
run 3 with 3
run 7 with 9 8 -> 3
run 4 with 3
test jump in position mode
run 3 with 12
run 6 with False -> 9
run 4 with 13
run 3 with 12
run 1 with 0 1 -> 13
run 4 with 13
test jump in immediate mode
run 3 with 3
run 1 with 0 0 -> 12
run 4 with 12
run 3 with 3
run 5 with True -> 9
run 4 with 12
test bigger example
run 3 with 21
run 8 with 8 8 -> 20
run 5 with True -> 22
run 2 with 8 125 -> 20
run 4 with 20
run 3 with 21
run 8 with 9 8 -> 20
run 7 with 8 9 -> 20
run 6 with False -> 36
run 1 with 1000 1 -> 20
run 4 with 20

In [166]:
i5

[3,
 225,
 1,
 225,
 6,
 6,
 1100,
 1,
 238,
 225,
 104,
 0,
 1101,
 37,
 34,
 224,
 101,
 -71,
 224,
 224,
 4,
 224,
 1002,
 223,
 8,
 223,
 101,
 6,
 224,
 224,
 1,
 224,
 223,
 223,
 1002,
 113,
 50,
 224,
 1001,
 224,
 -2550,
 224,
 4,
 224,
 1002,
 223,
 8,
 223,
 101,
 2,
 224,
 224,
 1,
 223,
 224,
 223,
 1101,
 13,
 50,
 225,
 102,
 7,
 187,
 224,
 1001,
 224,
 -224,
 224,
 4,
 224,
 1002,
 223,
 8,
 223,
 1001,
 224,
 5,
 224,
 1,
 224,
 223,
 223,
 1101,
 79,
 72,
 225,
 1101,
 42,
 42,
 225,
 1102,
 46,
 76,
 224,
 101,
 -3496,
 224,
 224,
 4,
 224,
 102,
 8,
 223,
 223,
 101,
 5,
 224,
 224,
 1,
 223,
 224,
 223,
 1102,
 51,
 90,
 225,
 1101,
 11,
 91,
 225,
 1001,
 118,
 49,
 224,
 1001,
 224,
 -140,
 224,
 4,
 224,
 102,
 8,
 223,
 223,
 101,
 5,
 224,
 224,
 1,
 224,
 223,
 223,
 2,
 191,
 87,
 224,
 1001,
 224,
 -1218,
 224,
 4,
 224,
 1002,
 223,
 8,
 223,
 101,
 4,
 224,
 224,
 1,
 224,
 223,
 223,
 1,
 217,
 83,
 224,
 1001,
 224,
 -124,
 224,
 4,
 224,
 1002,
 223,
 8,
 223,
 101,
 5,
 224,
 224,
 1,
 223,
 224,
 223,
 1101,
 32,
 77,
 225,
 1101,
 29,
 80,
 225,
 101,
 93,
 58,
 224,
 1001,
 224,
 -143,
 224,
 4,
 224,
 102,
 8,
 223,
 223,
 1001,
 224,
 4,
 224,
 1,
 223,
 224,
 223,
 1101,
 45,
 69,
 225,
 4,
 223,
 99,
 0,
 0,
 0,
 677,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1105,
 0,
 99999,
 1105,
 227,
 247,
 1105,
 1,
 99999,
 1005,
 227,
 99999,
 1005,
 0,
 256,
 1105,
 1,
 99999,
 1106,
 227,
 99999,
 1106,
 0,
 265,
 1105,
 1,
 99999,
 1006,
 0,
 99999,
 1006,
 227,
 274,
 1105,
 1,
 99999,
 1105,
 1,
 280,
 1105,
 1,
 99999,
 1,
 225,
 225,
 225,
 1101,
 294,
 0,
 0,
 105,
 1,
 0,
 1105,
 1,
 99999,
 1106,
 0,
 300,
 1105,
 1,
 99999,
 1,
 225,
 225,
 225,
 1101,
 314,
 0,
 0,
 106,
 0,
 0,
 1105,
 1,
 99999,
 7,
 226,
 226,
 224,
 102,
 2,
 223,
 223,
 1005,
 224,
 329,
 101,
 1,
 223,
 223,
 108,
 677,
 226,
 224,
 102,
 2,
 223,
 223,
 1005,
 224,
 344,
 1001,
 223,
 1,
 223,
 1108,
 226,
 677,
 224,
 102,
 2,
 223,
 223,
 1005,
 224,
 359,
 1001,
 223,
 1,
 223,
 8,
 677,
 226,
 224,
 102,
 2,
 223,
 223,
 1006,
 224,
 374,
 1001,
 223,
 1,
 223,
 107,
 226,
 226,
 224,
 102,
 2,
 223,
 223,
 1006,
 224,
 389,
 101,
 1,
 223,
 223,
 1108,
 677,
 226,
 224,
 1002,
 223,
 2,
 223,
 1005,
 224,
 404,
 1001,
 223,
 1,
 223,
 108,
 677,
 677,
 224,
 102,
 2,
 223,
 223,
 1005,
 224,
 419,
 101,
 1,
 223,
 223,
 7,
 226,
 677,
 224,
 1002,
 223,
 2,
 223,
 1006,
 224,
 434,
 1001,
 223,
 1,
 223,
 107,
 226,
 677,
 224,
 102,
 2,
 223,
 223,
 1005,
 224,
 449,
 101,
 1,
 223,
 223,
 1108,
 677,
 677,
 224,
 1002,
 223,
 2,
 223,
 1006,
 224,
 464,
 101,
 1,
 223,
 223,
 7,
 677,
 226,
 224,
 102,
 2,
 223,
 223,
 1006,
 224,
 479,
 101,
 1,
 223,
 223,
 1007,
 677,
 677,
 224,
 1002,
 223,
 2,
 223,
 1005,
 224,
 494,
 101,
 1,
 223,
 223,
 1008,
 226,
 226,
 224,
 102,
 2,
 223,
 223,
 1006,
 224,
 509,
 1001,
 223,
 1,
 223,
 107,
 677,
 677,
 224,
 102,
 2,
 223,
 223,
 1006,
 224,
 524,
 1001,
 223,
 1,
 223,
 8,
 226,
 226,
 224,
 1002,
 223,
 2,
 223,
 1005,
 224,
 539,
 1001,
 223,
 1,
 223,
 1007,
 677,
 226,
 224,
 102,
 2,
 223,
 223,
 1006,
 224,
 554,
 1001,
 223,
 1,
 223,
 1007,
 226,
 226,
 224,
 1002,
 223,
 2,
 223,
 1005,
 224,
 569,
 1001,
 223,
 1,
 223,
 8,
 226,
 677,
 224,
 1002,
 223,
 2,
 223,
 1006,
 224,
 584,
 101,
 1,
 223,
 223,
 108,
 226,
 226,
 224,
 1002,
 223,
 2,
 223,
 1006,
 224,
 599,
 101,
 1,
 223,
 223,
 1107,
 677,
 226,
 224,
 1002,
 223,
 2,
 223,
 1005,
 224,
 614,
 1001,
 223,
 1,
 223,
 1107,
 226,
 677,
 224,
 102,
 2,
 223,
 223,
 1006,
 224,
 629,
 1001,
 223,
 1,
 223,
 1008,
 226,
 677,
 224,
 102,
 2,
 223,
 223,
 1005,
 224,
 644,
 101,
 1,
 223,
 223,
 1107,
 226,
 226,
 224,
 102,
 2,
 223,
 223,
 1006,
 224,
 659,
 1001,
 223,
 1,
 223,
 1008,
 677,
 677,
 224,
 102,
 2,
 223,
 223,
 1006,
 224,
 674,
 1001,
 223,
 1,
 223,
 4,
 223,
 99,
 226]

In [31]:
len(i5)

678

In [119]:
def get_modes(modes):
    return [int(mode) for mode in [modes[2], modes[1], modes[0], modes[3:]]]


def get_param(mode, increment, idx, data):
    if mode == 0:
        return data[data[idx + increment]]
    return data[idx + increment]

def get_params(mode1, mode2, idx, data):
    return get_param(mode1, 1, idx, data), get_param(mode2, 2, idx, data)


def add(mode1, mode2, idx, data):
    param1, param2 = get_params(mode1, mode2, idx, data)
    data[data[idx + 3]] = param1 + param2

def multiply(mode1, mode2, idx, data):
    param1, param2 = get_params(mode1, mode2, idx, data)
    data[data[idx + 3]] = param1 * param2

def less_than(mode1, mode2, idx, data):
    param1, param2 = get_params(mode1, mode2, idx, data)
    data[data[idx + 3]] = 1 if param1 < param2 else 0

def equals(mode1, mode2, idx, data):
    param1, param2 = get_params(mode1, mode2, idx, data)
    data[data[idx + 3]] = 1 if param1 == param2 else 0

def jump_if_true(mode1, mode2, idx, data):
    param1, param2 = get_params(mode1, mode2, idx, data)
    return param2 if param1 != 0 else idx + 3

def jump_if_false(mode1, mode2, idx, data):
    param1, param2 = get_params(mode1, mode2, idx, data)
    return param2 if param1 == 0 else idx + 3


def calculate(data, input_val):
    idx = 0
    diagnostic_code = None
    while data[idx] != 99:
        mode1, mode2, mode3, opcode = get_modes(f"{data[idx]:05}")
        if opcode == 1:
            add(mode1, mode2, idx, data)
            idx += 4
        elif opcode == 2:
            multiply(mode1, mode2, idx, data)
            idx += 4
        elif opcode == 3:
            data[data[idx+1]] = input_val
            idx += 2
        elif opcode == 4:
            diagnostic_code = data[data[idx + 1]]
            idx += 2
        elif opcode == 5:
            idx = jump_if_true(mode1, mode2, idx, data)
        elif opcode == 6:
            idx = jump_if_false(mode1, mode2, idx, data)
        elif opcode == 7:
            less_than(mode1, mode2, idx, data)
            idx += 4
        elif opcode == 8:
            equals(mode1, mode2, idx, data)
            idx += 4
    return diagnostic_code

In [128]:
calculate(mk_code(g), 9)

1001